### ISSUE TITLE
您好，请教两个问题

### ISSUE THREAD

**Issue by ChaliceRunRunRun** [Redaimao/DRPL#1]
您好，最近在复现您的代码，请问utils下是不是没有定义MyDataset_Raw_Blur方法，导入时找不到;
而且数据集的名字是否有问题，.pkl文件中有blur字段，图片名字中没有

**Comment by Redaimao** [comment]
> 您好，最近在复现您的代码，请问utils下是不是没有定义MyDataset_Raw_Blur方法，导入时找不到;
> 而且数据集的名字是否有问题，.pkl文件中有blur字段，图片名字中没有

你好，您可以尝试一下用MyDataset_Gradient，代码没有来及更新，后续我会重新检查一下有没有遗漏的地方。谢谢您的提问。

**Comment by ChaliceRunRunRun** [comment]
> > 您好，最近在复现您的代码，请问utils下是不是没有定义MyDataset_Raw_Blur方法，导入时找不到;
> > 而且数据集的名字是否有问题，.pkl文件中有blur字段，图片名字中没有
> 
> 你好，您可以尝试一下用MyDataset_Gradient，代码没有来及更新，后续我会重新检查一下有没有遗漏的地方。谢谢您的提问。

好的，十分感谢！
