### ISSUE TITLE
求求你更新一下代码吧

### ISSUE THREAD

**Issue by zyqflx** [Redaimao/DRPL#2]

**Comment by Redaimao** [comment]
你好，这份代码在train.py 里面应该使用第90，91行， 其他部分暂时没有发现问题，由于代码是在pytorch0.4版本上建立的，使用新的pytorh可能有一些小问题，您需要作相应的修改，谢谢

**Comment by zyqflx** [comment]
您好请问drpl这篇论文您是否方便分享一下中文稿呢？

**Comment by zyqflx** [comment]
还有一个问题想请教下，您提供的代码是该项目的全部代码吗？还是只有用于处理原始数据生成对掩膜的代码？

**Comment by Redaimao** [comment]
Hi, 
抱歉， 我们没有中文版的论文。代码是全部的代码
